- name: Reboot Linux with options
  hosts: linux
  serial: [1, 3, 10]
  become: yes

  tasks:
    - name: Reboot linux hosts
      reboot:
        connect_timeout: 30
        msg: Rebooting
        post_reboot_delay: 1
        pre_reboot_delay: 61
        test_command: uptime
        reboot_timeout: 500

- name: Reboot Windows with options
  hosts: windows
  become: yes

  tasks:
    - name: Reboot windows hosts
      win_reboot:
        connect_timeout: 30
        msg: Rebooting
        post_reboot_delay: 1
        pre_reboot_delay: 61
        test_command: uptime
        reboot_timeout: 500
