lab:
  hosts:
    lab-rhel7:
      ansible_host: 10.77.1.32
    lab-deb8:
      ansible_host: 10.77.1.39
    lab-alpine:
      ansible_host: 10.77.1.31
    lab-win2k16:
      ansible_host: 10.77.1.40

rhel:
  hosts:
    lab-rhel7:

debian:
  hosts:
    lab-deb8:

linux:
  children:
    rhel:
    debian:
  hosts:
    lab-alpine:

windows:
  hosts:
    lab-win2k16:
